In [66]:
%run qboot

# Operator Algebra

## Majorana Operator

Create Majorana operator by

In [2]:
maj()

I

In [3]:
maj(1)

χ1

Product of Majorana operators

In [4]:
(maj(1)@maj(1), maj(1)@maj(2), maj(2)@maj(1))

(I, χ1 χ2, - χ1 χ2)

Majorana operator product can be simply created as

In [5]:
maj(1,2,3,4)

χ1 χ2 χ3 χ4

In [6]:
maj(1,2,4,5)@maj(3,4,6,7)

- χ1 χ2 χ3 χ5 χ6 χ7

Scalar multiplication

In [7]:
2.5*maj(1), maj(1)/2, 1j*maj(1)@maj(2)

(2.50 χ1, 0.50 χ1, i χ1 χ2)

More general linear combination of Majorana operators

In [26]:
A = 0.5*maj(1,2,3,4) + 0.2*maj(5,6,7,8) - 0.1*maj(1,2,5,6)
B = 0.3*maj(3,4,5,6) - 0.6*maj(1,2,5,6)
A, B

(0.50 χ1 χ2 χ3 χ4 +0.20 χ5 χ6 χ7 χ8 -0.10 χ1 χ2 χ5 χ6,
 0.30 χ3 χ4 χ5 χ6 -0.60 χ1 χ2 χ5 χ6)

In [27]:
A@B

-0.15 χ1 χ2 χ5 χ6 +0.30 χ3 χ4 χ5 χ6 -0.06 χ3 χ4 χ7 χ8 +0.12 χ1 χ2 χ7 χ8 +0.03 χ1 χ2 χ3 χ4 +0.06 I

Inner product and trace

In [28]:
A.inner(B)

0.06

In [29]:
(A.H@B).trace()

0.06

Terms cancle out under subtraction.

In [30]:
A - A

0

Compare operator: operators are equal if their difference is zero

In [31]:
(A == A, A - A == 0, A != B)

(True, True, True)

A scalar is treated as the scalar times identity operator

In [32]:
maj(1) + 1

χ1 + I

In [35]:
maj() == 1

True

Round off small terms: `.round(decimals)` round to the specific number of decimal places (default: 0). 

In [36]:
(1.e-15*maj(1)+maj(2)).round(10)

χ2

Hermitian conjugation of operators

In [37]:
(maj(1,2), maj(1,2).H, maj(1,2).real, maj(1,2).imag)

(χ1 χ2, - χ1 χ2, 0, -i χ1 χ2)

### Fermion Parity

`.parity` returns the Fermion parity of the operator:
* +1: even
* -1: odd
* 0: mixed

In [38]:
maj(1).parity, maj(1,2).parity, (maj(1)@maj(2)@maj(3)).parity

(-1, 1, -1)

In [39]:
(maj(1)+1).parity

0

A cache variable `._parity` is introduced to keep the parity result

In [40]:
x = maj(1)
x._parity, x.parity, x._parity

(None, -1, -1)

The cache is cleared if the operator is modified.

In [41]:
x += 1
x._parity, x.parity, x._parity

(None, 0, 0)

### Locality and Commutator

In [64]:
H=sum(1j*maj(i)@maj((i+1)%4) for i in range(4))
H

i χ0 χ1 +i χ1 χ2 +i χ2 χ3 -i χ0 χ3

`.loc_terms` (local terms) hosts lists of terms for each location. This can be useful in calculating the commutator, as non-overlapping operators (with even fermion parity) always commute.

In [48]:
H.loc_terms

{0: {(0, 1), (0, 3)},
 1: {(0, 1), (1, 2)},
 2: {(1, 2), (2, 3)},
 3: {(0, 3), (2, 3)}}

Commutator

In [61]:
maj(1).commutate(maj(1)), maj(1).commutate(maj(2)), maj(1,2).commutate(maj(3))

(0, 2 χ1 χ2, 0)

In [65]:
H.commutate(maj(1,2))

2i χ0 χ2 -2i χ1 χ3

cache variables are populated after computing the commutator

In [51]:
H.__dict__

{'terms': {(0, 1): 1j, (1, 2): 1j, (2, 3): 1j, (0, 3): (-0-1j)},
 '_loc_terms': {0: {(0, 1), (0, 3)},
  1: {(0, 1), (1, 2)},
  2: {(1, 2), (2, 3)},
  3: {(0, 3), (2, 3)}},
 '_parity': 1}

## Pauli Operator

Pauli operator can be created in multiple ways

In [52]:
pauli(0), pauli(1), pauli(2), pauli(3)

(I, X0, Y0, Z0)

In [53]:
pauli('I'), pauli('X'), pauli('Y'), pauli('Z') 

(I, X0, Y0, Z0)

In [54]:
pauli('X1 Z2'), pauli('- IXZI'), pauli('I5ZZIZX1Y')

(X1 Z2, - X1 Z2, X1 Y2 Z6 Z7 Z9)

In [55]:
pauli({1:'Z',5:'Y'}), pauli({1:3,5:2}), pauli((1,3),(5,2)), pauli(('Z',1),('Y',5))

(Z1 Y5, Z1 Y5, Z1 Y5, Z1 Y5)

In [56]:
pauli('I','Z','X','I','Y','I'), pauli(0,3,1,0,2,0), pauli('Z',1,'X','Y',4),

(Z1 X2 Y4, Z1 X2 Y4, Z1 X2 Y4)

In [57]:
pauli()

I

Product of Pauli operators

In [67]:
pauli('X')@pauli('Y'), pauli('XX')@pauli('YY'), pauli('X1Y2')@pauli('Z0X1')

(i Z0, - Z0 Z1, Z0 Y2)

Scalar multiplication

In [68]:
2.5*pauli('X'), pauli('Y')/2

(2.50 X0, 0.50 Y0)

More general linear combinations of Pauli operators

In [69]:
A = 0.5*pauli('Z0') + 0.2*pauli('Z1') - 0.1*pauli('Z2')
B = 0.3*pauli('X0X1') - 0.6*pauli('X1X2')
A, B

(0.50 Z0 +0.20 Z1 -0.10 Z2, 0.30 X0 X1 -0.60 X1 X2)

In [70]:
A@B

0.15i Y0 X1 -0.30 Z0 X1 X2 +0.06i X0 Y1 -0.12i Y1 X2 -0.03 X0 X1 Z2 +0.06i X1 Y2

In [71]:
1j*(A@B - B@A)

-0.30 Y0 X1 -0.12 X0 Y1 +0.24 Y1 X2 -0.12 X1 Y2

In [72]:
A.inner(A), A.inner(B)

(0.30000000000000004, 0)

In [73]:
A.trace()

0

Hermitian conjugate of operators

In [74]:
(A@B).H, (A@B).real, (A@B).imag

(-0.15i Y0 X1 -0.30 Z0 X1 X2 -0.06i X0 Y1 +0.12i Y1 X2 -0.03 X0 X1 Z2 -0.06i X1 Y2,
 -0.30 Z0 X1 X2 -0.03 X0 X1 Z2,
 0.15 Y0 X1 +0.06 X0 Y1 -0.12 Y1 X2 +0.06 X1 Y2)

### Locality and Commutator

In [80]:
pauli('X').commutate(pauli('Y')), pauli('Y').commutate(pauli('X'))

(2i Z0, -2i Z0)

In [81]:
xy = pauli('X')+pauli('Y')
z = pauli('Z')
xy.commutate(z), z.commutate(xy)

(2i X0 -2i Y0, -2i X0 +2i Y0)

In [75]:
H = -sum(pauli(('Z',i),('Z',(i+1)%4)) for i in range(4))-sum(pauli('X',i) for i in range(4))
H

- Z0 Z1 - Z1 Z2 - Z2 Z3 - Z0 Z3 - X0 - X1 - X2 - X3

`.loc_terms` collects operator terms that cover each local position.

In [76]:
H.loc_terms

{0: {((0, 1),), ((0, 3), (1, 3)), ((0, 3), (3, 3))},
 1: {((0, 3), (1, 3)), ((1, 1),), ((1, 3), (2, 3))},
 2: {((1, 3), (2, 3)), ((2, 1),), ((2, 3), (3, 3))},
 3: {((0, 3), (3, 3)), ((2, 3), (3, 3)), ((3, 1),)}}

Commutator 

In [77]:
H.commutate(pauli('X1'))

-2i Z0 Y1 -2i Y1 Z2

In [78]:
H.commutate(H)

0

# Operator Space

## Operator Signature

Dot product of operator:
* ordinary (non-Hermitian) dot product (no operator is conjugated)
$$A\cdot B=\frac{1}{\mathrm{Tr}\mathbb{1}}\mathrm{Tr}(A B)$$
* Hermitian dot product (left operator conjugated)
$$A\cdot_H B=\frac{1}{\mathrm{Tr}\mathbb{1}}\mathrm{Tr}(A^\dagger B)$$

Positivity:
* $A\cdot A$ is **not** positive definite, its sign is defined as the signature of $A$. 
* $A\cdot_H A$ is positive definite
* One may define $\text{signature}(A)=\mathrm{Tr}A^2/\mathrm{Tr}(A^\dagger A)$. If $A^2=\pm \mathbb{1}$, then $A^\dagger = \text{signature}(A) A$.

In [82]:
ops = [maj(range(n)) for n in range(5)]
ops

[I, χ0, χ0 χ1, χ0 χ1 χ2, χ0 χ1 χ2 χ3]

Operator may not have positive signature

In [83]:
[[(op1@op2).trace() for op2 in ops] for op1 in ops]

[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, -1, 0, 0],
 [0, 0, 0, -1, 0],
 [0, 0, 0, 0, 1]]

In [86]:
[[(op1.H@op2).trace() for op2 in ops] for op1 in ops]

[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]

Inner product corresponds to the Hermitian dot product.

In [87]:
[[op1.inner(op2) for op2 in ops] for op1 in ops]

[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]

## Operators

Construct an array of operators

In [88]:
ops = Operators([maj(range(n)) for n in range(5)])
ops

Operators([I, χ0, χ0 χ1, χ0 χ1 χ2, χ0 χ1 χ2 χ3])

In [91]:
ops[1], ops[:2], ops[numpy.array([0,3])]

(χ0, Operators([I, χ0]), Operators([I, χ0 χ1 χ2]))

Element-wise properties and functions.

In [92]:
ops.H, ops.real, ops.imag

(Operators([I, χ0, - χ0 χ1, - χ0 χ1 χ2, χ0 χ1 χ2 χ3]),
 Operators([I, χ0, 0, 0, χ0 χ1 χ2 χ3]),
 Operators([0, 0, -i χ0 χ1, -i χ0 χ1 χ2, 0]))

In [93]:
ops.trace(), ops.norm()

(array([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]),
 array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]))

In [94]:
ops.normalize(), ops.round()

(Operators([I, χ0, χ0 χ1, χ0 χ1 χ2, χ0 χ1 χ2 χ3]),
 Operators([I, χ0, χ0 χ1, χ0 χ1 χ2, χ0 χ1 χ2 χ3]))

Element-wise binary operation

In [95]:
ops + 3*ops # element wise 

Operators([4 I, 4 χ0, 4 χ0 χ1, 4 χ0 χ1 χ2, 4 χ0 χ1 χ2 χ3])

In [97]:
ops.inner(ops), ops.inner(maj())

(array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]),
 array([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]))

In [98]:
x = numpy.arange(5)
ops.dot(x), x.dot(ops)

(χ0 +2 χ0 χ1 +3 χ0 χ1 χ2 +4 χ0 χ1 χ2 χ3,
 χ0 +2 χ0 χ1 +3 χ0 χ1 χ2 +4 χ0 χ1 χ2 χ3)

In [99]:
ops + maj(), maj() + ops

(Operators([2 I, χ0 + I, χ0 χ1 + I, χ0 χ1 χ2 + I, χ0 χ1 χ2 χ3 + I]),
 Operators([2 I, χ0 + I, χ0 χ1 + I, χ0 χ1 χ2 + I, χ0 χ1 χ2 χ3 + I]))

`Operators` object of a single operator (as scalar) falls back to an `Operator` object

In [100]:
Operators(maj())

I

Select subspace

In [101]:
ops[ops == 1], ops[ops != 1]

(Operators([I]), Operators([χ0, χ0 χ1, χ0 χ1 χ2, χ0 χ1 χ2 χ3]))

In [102]:
ops[ops.weight() <= 2]

Operators([I, χ0, χ0 χ1])

## OperatorSpace

Start with a base space of operators

In [103]:
ops0 = OperatorSpace([maj()])
ops0

OperatorSpace([I])

In [105]:
ops1 = ops0.append([maj(i) for i in range(4)])
ops1

OperatorSpace([I, χ0, χ1, χ2, χ3])

represent an operator in the operator space

In [106]:
v = ops1.represent(maj(1))
v

array([0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j])

reconstruct operator from its representation

In [107]:
ops1.reconstruct(v)

χ1

represent an array of operators in the operator space

In [110]:
a = Operators([[maj(0),maj(1)],[maj(2),maj(3)]])
a

Operators([[χ0, χ1],
           [χ2, χ3]])

In [111]:
m = ops1.represent(a)
m

array([[[0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]]])

In [112]:
ops1.reconstruct(m)

Operators([[χ0, χ1],
           [χ2, χ3]])

Use `outer` to obtain multiplication table of basis operators.

In [113]:
ope = ops1.outer(ops1)
ope

Operators([[I, χ0, χ1, χ2, χ3],
           [χ0, I, χ0 χ1, χ0 χ2, χ0 χ3],
           [χ1, - χ0 χ1, I, χ1 χ2, χ1 χ3],
           [χ2, - χ0 χ2, - χ1 χ2, I, χ2 χ3],
           [χ3, - χ0 χ3, - χ1 χ3, - χ2 χ3, I]])

Construct orthonormal basis

In [114]:
ope.orth()

OperatorSpace([I, χ1, χ2, χ3, χ0 χ1, χ0 χ2, χ0 χ3, χ1 χ2, χ1 χ3, χ2 χ3,
               χ0])

Solve for null operators that are not in the smaller operator space (new operators generated by operator product)

In [115]:
ope.orth().solve(ops1)

OperatorSpace([χ0 χ2, χ0 χ3, χ1 χ2, χ1 χ3, χ2 χ3, χ0 χ1])

Extend to a larger space, including new operators generated by ope. The basis are automatically orthonormalized.

In [116]:
ops2 = ops1.append(ope.orth().solve(ops1))
ops2

OperatorSpace([I, χ0, χ1, χ2, χ3, χ0 χ2, χ0 χ3, χ1 χ2, χ1 χ3, χ2 χ3,
               χ0 χ1])

It is better to choose a Hermitian basis, which can be done by Hermitianization.

In [117]:
ops2 = ops2.real - ops2.imag
ops2

OperatorSpace([I, χ0, χ1, χ2, χ3, i χ0 χ2, i χ0 χ3, i χ1 χ2, i χ1 χ3,
               i χ2 χ3, i χ0 χ1])

Represent the OPE result in the larger operator space, which gives the fusion tensor

In [118]:
ops2.represent(ope, axis=0).shape

(11, 5, 5)

Create a Hamiltonian

In [119]:
H = sum(1j*maj(i)@maj((i+1)%4) for i in range(4))
H

i χ0 χ1 +i χ1 χ2 +i χ2 χ3 -i χ0 χ3

represent it in the full space

In [120]:
ops2.represent(H)

array([ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j,
        1.+0.j,  0.+0.j,  1.+0.j,  1.+0.j])

Compute commutator to obtain constraint equatitions

In [121]:
eqs = ops2[ops2 != 1].adjoint(H)
eqs

OperatorSpace([2 χ1 -2 χ3, -2 χ0 +2 χ2, -2 χ1 +2 χ3, 2 χ0 -2 χ2,
               2i χ1 χ2 +2i χ2 χ3 +2i χ0 χ3 -2i χ0 χ1, 2i χ1 χ3 -2i χ0 χ2,
               -2i χ0 χ2 +2i χ1 χ3,
               -2i χ0 χ3 -2i χ0 χ1 -2i χ1 χ2 +2i χ2 χ3,
               -2i χ1 χ3 -2i χ0 χ2, 2i χ1 χ3 +2i χ0 χ2])

Pick out non-trivial equations (remove zeros)

In [122]:
eqs1 = eqs[eqs != 0]
eqs1

OperatorSpace([2 χ1 -2 χ3, -2 χ0 +2 χ2, -2 χ1 +2 χ3, 2 χ0 -2 χ2,
               2i χ1 χ2 +2i χ2 χ3 +2i χ0 χ3 -2i χ0 χ1, 2i χ1 χ3 -2i χ0 χ2,
               -2i χ0 χ2 +2i χ1 χ3,
               -2i χ0 χ3 -2i χ0 χ1 -2i χ1 χ2 +2i χ2 χ3,
               -2i χ1 χ3 -2i χ0 χ2, 2i χ1 χ3 +2i χ0 χ2])

Moreover, the identity operator has a fixed expectation value, it should also be constrained (although not constrained to zero). Impose this constraint by adding identity operator to the equations.

In [124]:
eqs2 = eqs[eqs != 0].append(maj())
eqs2

OperatorSpace([2 χ1 -2 χ3, -2 χ0 +2 χ2, -2 χ1 +2 χ3, 2 χ0 -2 χ2,
               2i χ1 χ2 +2i χ2 χ3 +2i χ0 χ3 -2i χ0 χ1, 2i χ1 χ3 -2i χ0 χ2,
               -2i χ0 χ2 +2i χ1 χ3,
               -2i χ0 χ3 -2i χ0 χ1 -2i χ1 χ2 +2i χ2 χ3,
               -2i χ1 χ3 -2i χ0 χ2, 2i χ1 χ3 +2i χ0 χ2, I])

represent equations in the full operator space

In [126]:
eqmat1 = ops2[ops2 != 1].represent(eqs1)
eqmat1.real

array([[ 0.,  2.,  0., -2.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-2.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -2.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  0., -2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  2.,  2.,  0.,  2., -2.],
       [ 0.,  0.,  0.,  0., -2.,  0.,  0.,  2.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -2.,  0.,  0.,  2.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -2., -2.,  0.,  2., -2.],
       [ 0.,  0.,  0.,  0., -2.,  0.,  0., -2.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  2.,  0.,  0.,  2.,  0.,  0.]])

In [127]:
eqmat2 = ops2.represent(eqs2)
eqmat2.real

array([[ 0.,  0.,  2.,  0., -2.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -2.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -2.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0., -2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  2.,  2.,  0.,  2., -2.],
       [ 0.,  0.,  0.,  0.,  0., -2.,  0.,  0.,  2.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -2.,  0.,  0.,  2.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -2., -2.,  0.,  2., -2.],
       [ 0.,  0.,  0.,  0.,  0., -2.,  0.,  0., -2.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,  2.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

Find null space. Null vectors form the projection operator that project to the null space, in which the constrains are satisfied.

In [131]:
import scipy
proj = scipy.linalg.null_space(eqmat2.real)
print(numpy.array_repr(proj,suppress_small=True))

array([[ 0.        , -0.        , -0.        , -0.        ],
       [ 0.        , -0.        , -0.70710678, -0.        ],
       [ 0.        , -0.        ,  0.        , -0.70710678],
       [ 0.        ,  0.        , -0.70710678,  0.        ],
       [ 0.        , -0.        ,  0.        , -0.70710678],
       [ 0.        , -0.        ,  0.        , -0.        ],
       [ 0.        , -0.70710678,  0.        , -0.        ],
       [ 0.        ,  0.70710678,  0.        , -0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.70710678, -0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.        ,  0.        ,  0.        ]])


In [132]:
eqmat2.shape, proj.shape

((11, 11), (11, 4))

Reduced operators in the null space.

In [133]:
ops2.reconstruct(proj.round(10), axis=0)

Operators([0.71i χ2 χ3 +0.71i χ0 χ1, -0.71i χ0 χ3 +0.71i χ1 χ2,
           -0.71 χ0 -0.71 χ2, -0.71 χ1 -0.71 χ3])

Reconstruct reduced operator space (including the identity operator)

In [135]:
ops3 = OperatorSpace([maj()]).append(ops2.reconstruct(proj.round(10), axis=0))
ops3

OperatorSpace([I, 0.71i χ2 χ3 +0.71i χ0 χ1, -0.71i χ0 χ3 +0.71i χ1 χ2,
               -0.71 χ0 -0.71 χ2, -0.71 χ1 -0.71 χ3])

Represent the Hamiltonian and OPE matrix in the reduced operator space

In [136]:
h = ops3.represent(H)
M = ops3.represent(ope, axis=0)
print(numpy.array_repr(h,precision=4))
print(numpy.array_repr(M,precision=1, suppress_small=True))

array([0.    +0.j, 1.4142+0.j, 1.4142+0.j, 0.    +0.j, 0.    +0.j])
array([[[ 1. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
        [ 0. +0.j ,  1. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
        [ 0. +0.j ,  0. +0.j ,  1. +0.j ,  0. +0.j ,  0. +0.j ],
        [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  1. +0.j ,  0. +0.j ],
        [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  1. +0.j ]],

       [[ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
        [ 0. +0.j ,  0. +0.j ,  0. -0.7j,  0. +0.j ,  0. +0.j ],
        [ 0. +0.j ,  0. +0.7j,  0. +0.j ,  0. +0.j ,  0. +0.j ],
        [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. -0.7j],
        [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.7j,  0. +0.j ]],

       [[ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ],
        [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.7j],
        [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  0. -0.7j,  0. +0.j ],
        [ 0. +0.j ,  0. +0.j ,  0. +0.7j,  0. +0.j ,  0. +0.j ],
        [ 0. +0.j 

In [137]:
from qboot import SDP
E, x = SDP(h[1:].real, M[0], M[1:])
E, x

(-1.9999999999859985,
 array([-7.07106781e-01, -7.07106781e-01,  7.62755857e-33, -2.46835709e-32]))

In [139]:
ops2.represent(ops3[ops3 != 1], axis=0) @ x

array([ 0.00000000e+00+0.j, -5.39349839e-33+0.j,  1.74539204e-32+0.j,
       -5.39349839e-33+0.j,  1.74539204e-32+0.j,  0.00000000e+00+0.j,
        5.00000000e-01+0.j, -5.00000000e-01+0.j,  0.00000000e+00+0.j,
       -5.00000000e-01+0.j, -5.00000000e-01+0.j])

Solve equations to find null operator space, using different operator space and equations

In [141]:
ops2[ops2 != 1].solve(eqs).round(10)

OperatorSpace([-0.55 χ0 -0.44 χ1 -0.55 χ2 -0.44 χ3,
               -0.71i χ0 χ3 +0.71i χ1 χ2,
               -0.44 χ0 +0.55 χ1 -0.44 χ2 +0.55 χ3,
               0.71i χ2 χ3 +0.71i χ0 χ1])

In [142]:
ops2.solve(eqs).round(10)

OperatorSpace([- I, 0.37 χ0 -0.60 χ1 +0.37 χ2 -0.60 χ3,
               -0.35 χ0 -0.21 χ1 -0.35 χ2 -0.21 χ3 +0.58i χ0 χ3 -0.58i χ1 χ2,
               0.49 χ0 +0.30 χ1 +0.49 χ2 +0.30 χ3 +0.41i χ0 χ3 -0.41i χ1 χ2,
               0.71i χ2 χ3 +0.71i χ0 χ1])

In [143]:
ops2.solve(eqs.append(maj())).round(10)

OperatorSpace([0.71i χ2 χ3 +0.71i χ0 χ1, -0.71i χ0 χ3 +0.71i χ1 χ2,
               -0.71 χ0 -0.71 χ2, -0.71 χ1 -0.71 χ3])

Results are different but equivalenet.

In [1]:
%run qboot

In [3]:
ops = OperatorSpace([maj()])
ops = ops.append([1j*maj(i+1,j+1) for i,j in combinations(range(4),2)])
ops = ops.append(maj(1,2,3,4))
ops

OperatorSpace([I, i χ1 χ2, i χ1 χ3, i χ1 χ4, i χ2 χ3, i χ2 χ4, i χ3 χ4,
               χ1 χ2 χ3 χ4])

In [4]:
ope = ops.outer(ops)
ope

Operators([[I, i χ1 χ2, i χ1 χ3, i χ1 χ4, i χ2 χ3, i χ2 χ4, i χ3 χ4,
            χ1 χ2 χ3 χ4],
           [i χ1 χ2, I, χ2 χ3, χ2 χ4, - χ1 χ3, - χ1 χ4, - χ1 χ2 χ3 χ4,
            -i χ3 χ4],
           [i χ1 χ3, - χ2 χ3, I, χ3 χ4, χ1 χ2, χ1 χ2 χ3 χ4, - χ1 χ4,
            i χ2 χ4],
           [i χ1 χ4, - χ2 χ4, - χ3 χ4, I, - χ1 χ2 χ3 χ4, χ1 χ2, χ1 χ3,
            -i χ2 χ3],
           [i χ2 χ3, χ1 χ3, - χ1 χ2, - χ1 χ2 χ3 χ4, I, χ3 χ4, - χ2 χ4,
            -i χ1 χ4],
           [i χ2 χ4, χ1 χ4, χ1 χ2 χ3 χ4, - χ1 χ2, - χ3 χ4, I, χ2 χ3,
            i χ1 χ3],
           [i χ3 χ4, - χ1 χ2 χ3 χ4, χ1 χ4, - χ1 χ3, χ2 χ4, - χ2 χ3, I,
            -i χ1 χ2],
           [χ1 χ2 χ3 χ4, -i χ3 χ4, i χ2 χ4, -i χ2 χ3, -i χ1 χ4, i χ1 χ3,
            -i χ1 χ2, I]])

In [5]:
ops.represent(ope, axis=0)

array([[[ 1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
          0.+0.j],
        [ 0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
          0.+0.j],
        [ 0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
          0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
          0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j,
          0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j,
          0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  1.+0.j,
          0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
          1.+0.j]],

       [[ 0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
          0.+0.j],
        [ 1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
          0.+0.j],
        [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.-1.j,  0.+0.j,  0.+0.j,
          0.+0.j